In [1]:
# Basic Input and Output

name = input("Enter your name: ")
print(f"Hello, {name}!")

Enter your name: Chetan Chandra
Hello, Chetan Chandra!

In [2]:
# Finding Duplicate Records

data = ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Bob']

duplicates = set(x for x in data if data.count(x) > 1)
print("Duplicate records:", duplicates)

Duplicate records: {'Alice', 'Bob'}

In [4]:
# Finding Nth Highest Salary

salaries = [50000, 60000, 75000, 60000, 90000]

def nth_highest(salaries, n):
    unique_salaries = list(set(salaries))
    #sorted_salaries = unique_salaries.sort(reverse=True)
    sorted_salaries = sorted(unique_salaries, reverse=True)
    return sorted_salaries[n-1] if n <= len(sorted_salaries) else None

print("2nd highest salary:", nth_highest(salaries, 2))

2nd highest salary: 75000

In [5]:
# Deleting Duplicates and Finding Unique Records

data = ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Bob']

unique_data = list(set(data))
print("Unique records:", unique_data)

Unique records: ['Charlie', 'Alice', 'David', 'Bob']

In [37]:
# Ranking and Dense Ranking

import pandas as pd

salaries_df = pd.DataFrame({
                            'name': ['Alice', 'Bob', 'Charlie', 'David', 'Chetan', 'Shilpa', 'Misty'],
                            'salary': [50000, 60000, 75000, 60000, 75000, 75000, 80000]
                        })



salaries_df['rank']       = salaries_df['salary'].rank(method='min', ascending=False)
salaries_df['dense_rank'] = salaries_df['salary'].rank(method='dense', ascending=False)


print(salaries_df.sort_values(by='dense_rank', ascending=True))

      name  salary  rank  dense_rank
6    Misty   80000   1.0         1.0
2  Charlie   75000   2.0         2.0
4   Chetan   75000   2.0         2.0
5   Shilpa   75000   2.0         2.0
1      Bob   60000   5.0         3.0
3    David   60000   5.0         3.0
0    Alice   50000   7.0         4.0

In [42]:
rank_1_df = salaries_df[salaries_df['rank'] == 1.0]
rank_1_df

    name  salary  rank  dense_rank
6  Misty   80000   1.0         1.0

In [44]:
rank_2_df = salaries_df[salaries_df['rank'] == 2.0]
rank_2_df

      name  salary  rank  dense_rank
2  Charlie   75000   2.0         2.0
4   Chetan   75000   2.0         2.0
5   Shilpa   75000   2.0         2.0

In [45]:
# Merging and Joining Tables

data1 = pd.DataFrame({
                        'name': ['Alice', 'Bob'],
                        'salary': [50000, 60000]
                    })

data2 = pd.DataFrame({
                        'name': ['Bob', 'Charlie'],
                        'department': ['HR', 'Engineering']
                    })

merged_data = pd.merge(data1, data2, on='name', how='inner')
print(merged_data)

  name  salary department
0  Bob   60000         HR

In [47]:
# Join

import pandas as pd

# Create the first DataFrame
data1 = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'salary': [50000, 60000]
}).set_index('name')  # Set 'name' as the index for joining

# Create the second DataFrame
data2 = pd.DataFrame({
    'name': ['Bob', 'Charlie'],
    'department': ['HR', 'Engineering']
}).set_index('name')  # Set 'name' as the index for joining

# Join the two DataFrames
joined_data = data1.join(data2, how='inner')

print(joined_data)

      salary department
name
Bob    60000         HR

In [1]:
# Counting Records

import pandas as pd

# Sample DataFrame
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'salary': [50000, 60000, 75000, 60000]
})

# Count records
total_records = employees.shape[0]
print("Total records:", total_records)

Total records: 4

In [7]:
# Group By and Aggregation

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'salary': [50000, 60000, 75000, 60000, 90000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT']
})

# Group by and calculate average salary
average_salary = employees.groupby('department')['salary'].mean().reset_index()
print("average_salary")
print(average_salary)
print("   ")

maximum_salary = employees.groupby('department')['salary'].max().reset_index()
print("maximum_salary")
print(maximum_salary)
print("   ")

minimum_salary = employees.groupby('department')['salary'].min().reset_index()
print("minimum_salary")
print(minimum_salary)

average_salary
    department   salary
0  Engineering  67500.0
1           HR  55000.0
2           IT  90000.0

maximum_salary
    department  salary
0  Engineering   75000
1           HR   60000
2           IT   90000

minimum_salary
    department  salary
0  Engineering   60000
1           HR   50000
2           IT   90000

In [8]:
# Filtering Records

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'salary': [50000, 60000, 75000, 60000, 90000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT']
})

# Filter records with salary greater than 60000
high_salary_employees = employees[employees['salary'] > 60000]
print(high_salary_employees)

      name  salary   department
2  Charlie   75000  Engineering
4      Eve   90000           IT

In [10]:
# Finding Maximum and Minimum Salary

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Chetan', 'Deba'],
    'salary': [50000, 60000, 75000, 60000, 90000, 90000, 50000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT' , 'IT', 'IT']
})

max_salary = employees['salary'].max()
min_salary = employees['salary'].min()
print("Max Salary:", max_salary)
print("Min Salary:", min_salary)

Max Salary: 90000
Min Salary: 50000

In [11]:
# Pivot Table

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Chetan', 'Deba'],
    'salary': [50000, 60000, 75000, 60000, 90000, 90000, 50000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT' , 'IT', 'IT']
})

# Create a pivot table
pivot_table = employees.pivot_table(index='department', values='name', aggfunc='count').reset_index()
pivot_table.columns = ['department', 'employee_count']
print(pivot_table)

    department  employee_count
0  Engineering               2
1           HR               2
2           IT               3

In [12]:
# Handling Missing Values

# Sample DataFrame with missing values
employees_with_na = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', None],
    'salary': [50000, None, 75000, 60000]
})

# Drop rows with missing salary
cleaned_employees = employees_with_na.dropna(subset=['salary'])
print(cleaned_employees)

      name   salary
0    Alice  50000.0
2  Charlie  75000.0
3     None  60000.0

In [13]:
# Sorting Records

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Chetan', 'Deba'],
    'salary': [50000, 60000, 75000, 60000, 90000, 90000, 50000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT' , 'IT', 'IT']
})

# Sort DataFrame by salary descending
sorted_employees = employees.sort_values(by='salary', ascending=False)
print(sorted_employees)

      name  salary   department
4      Eve   90000           IT
5   Chetan   90000           IT
2  Charlie   75000  Engineering
1      Bob   60000           HR
3    David   60000  Engineering
0    Alice   50000           HR
6     Deba   50000           IT

In [14]:
# Finding Unique Values

# Sample DataFrame with departments
employees = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Chetan', 'Deba'],
    'salary': [50000, 60000, 75000, 60000, 90000, 90000, 50000],
    'department': ['HR', 'HR', 'Engineering', 'Engineering', 'IT' , 'IT', 'IT']
})

# Find unique departments
unique_departments = employees['department'].unique()
print("Unique departments:", unique_departments)

Unique departments: ['HR' 'Engineering' 'IT']

In [15]:
# Date Filtering

# Sample DataFrame with hire dates
employees_with_dates = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'hire_date': pd.to_datetime(['2023-01-15', '2021-12-01'])
})

# Filter records based on hire date
recent_hires = employees_with_dates[employees_with_dates['hire_date'] > '2022-01-01']
print(recent_hires)

    name  hire_date
0  Alice 2023-01-15