## Step 1: Install Required Libraries

In [1]:
pip install pandas pyodbc

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: pyodbc in c:\users\admin\anaconda3\lib\site-packages (4.0.34)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (2.0.31)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pyodbc in c:\users\admin\anaconda3\lib\site-packages (4.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)

## Step 2: Connect to SQL Server

In [28]:
import pandas as pd
import pyodbc
from sqlalchemy import create_engine
import urllib

In [ ]:
# Define the connection string for pyodbc

conn_string = (
    "DRIVER={SQL Server};"
    "SERVER=CHETAN\SQLSERVER2022;"
    "DATABASE=AdventureWorksDW2022;"
#     "UID=your_username;"
#     "PWD=your_password;"
)

# Create a connection
conn = pyodbc.connect(conn_string)

In [32]:
# Define the connection string for SQLAlchemy

params = urllib.parse.quote_plus("DRIVER={SQL Server};"
                                  "SERVER=CHETAN\SQLSERVER2022;"
                                  "DATABASE=AdventureWorksDW2022;")
#                                   "UID=your_username;"
#                                   "PWD=your_password;")

# Create the SQLAlchemy engine
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [33]:
# Extract data from a table (e.g., DimProduct)
query = "SELECT * FROM DimProduct"
df_product = pd.read_sql(query, engine)
df_product

AttributeError: 'OptionEngine' object has no attribute 'execute'

## Step 3: Extract Data

In [11]:
# Extract data from a table (e.g., DimProduct)
query = "SELECT * FROM DimProduct"
df_product = pd.read_sql(query, conn)

# Adjust pandas settings to display all columns
#pd.set_option('display.max_columns', None)  # None means no limit
#pd.set_option('display.width', None)        # No limit on width

# Check the extracted data
print(df_product.head())

   ProductKey ProductAlternateKey  ProductSubcategoryKey  \
0           1             AR-5381                    NaN
1           2             BA-8327                    NaN
2           3             BE-2349                    NaN
3           4             BE-2908                    NaN
4           5             BL-2036                    NaN

  WeightUnitMeasureCode SizeUnitMeasureCode     EnglishProductName  \
0                  None                None        Adjustable Race
1                  None                None           Bearing Ball
2                  None                None        BB Ball Bearing
3                  None                None  Headset Ball Bearings
4                  None                None                  Blade

  SpanishProductName FrenchProductName  StandardCost  FinishedGoodsFlag Color  \
0                                                NaN              False    NA
1                                                NaN              False    NA
2                                                NaN              False    NA
3                                                NaN              False    NA
4                                                NaN              False    NA

   SafetyStockLevel  ReorderPoint  ListPrice  Size SizeRange  Weight  \
0              1000           750        NaN  None        NA     NaN
1              1000           750        NaN  None        NA     NaN
2               800           600        NaN  None        NA     NaN
3               800           600        NaN  None        NA     NaN
4               800           600        NaN  None        NA     NaN

   DaysToManufacture ProductLine  DealerPrice Class Style ModelName  \
0                  0        None          NaN  None  None      None
1                  0        None          NaN  None  None      None
2                  1        None          NaN  None  None      None
3                  0        None          NaN  None  None      None
4                  1        None          NaN  None  None      None

                                          LargePhoto EnglishDescription  \
0  b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...               None
1  b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...               None
2  b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...               None
3  b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...               None
4  b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...               None

  FrenchDescription ChineseDescription ArabicDescription HebrewDescription  \
0              None               None              None              None
1              None               None              None              None
2              None               None              None              None
3              None               None              None              None
4              None               None              None              None

  ThaiDescription GermanDescription JapaneseDescription TurkishDescription  \
0            None              None                None               None
1            None              None                None               None
2            None              None                None               None
3            None              None                None               None
4            None              None                None               None

   StartDate EndDate   Status
0 2003-07-01     NaT  Current
1 2003-07-01     NaT  Current
2 2003-07-01     NaT  Current
3 2003-07-01     NaT  Current
4 2003-07-01     NaT  Current

C:\Users\Admin\AppData\Local\Temp\ipykernel_28280\3215009779.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_product = pd.read_sql(query, conn)

In [10]:
print(df_product.shape)

(606, 36)

## Step 4: Transform Data

In [12]:
# Example transformation: Filter products with a specific condition
df_transformed = df_product[df_product['Color'] == 'Black']

In [21]:
# Create a copy to avoid warnings
df_transformed = df_product[df_product['Color'] == 'Black'].copy()

In [23]:
df_transformed.head()

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,ListPrice,Size,SizeRange,Weight,DaysToManufacture,ProductLine,DealerPrice,Class,Style,ModelName,LargePhoto,EnglishDescription,FrenchDescription,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
5,6,CA-5965,NaN,None,None,LL Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,L,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current
6,7,CA-6738,NaN,None,None,ML Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,M,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current
7,8,CA-7457,NaN,None,None,HL Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,None,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current
10,11,CR-7833,NaN,None,None,Chainring,,,NaN,False,Black,1000,750,NaN,None,NA,NaN,0,None,NaN,None,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current
209,210,FR-R92B-58,14.0,LB,CM,"HL Road Frame - Black, 58",,,NaN,True,Black,500,375,NaN,58,54-58 CM,2.24,1,R,NaN,H,U,HL Road Frame,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,Our lightest and best quality aluminum frame m...,Notre cadre en aluminium plus léger et de qual...,重量最轻、质量最好的铝制车架采用最新的合金材质；经过焊接和热处理，坚固牢靠。我们创新的设计确...,لقد تم صناعة هيكل دراجتنا الألومنيوم الأخف وزن...,מסגרת האלומיניום הקלה והאיכותית ביותר שלנו עשו...,เฟรมอลูมิเนียมคุณภาพสูงสุดและน้ำหนักเบาที่สุด ...,Unser leichtester und hochwertigster Aluminium...,最新の合金で作られた最軽量/最高品質のアルミニウム フレームで、強度を得るために溶接および熱...,"""En yeni alaşımdan imal edilme, en hafif ve en...",2003-07-01,NaT,Current

In [19]:
# Additional transformation: Create a new column
df_transformed['Price'] = df_transformed['StandardCost'] * 1.2  # Example calculation

C:\Users\Admin\AppData\Local\Temp\ipykernel_28280\680822220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['Price'] = df_transformed['StandardCost'] * 1.2  # Example calculation

In [24]:
# Use .loc to assign the new column
df_transformed.loc[:, 'Price'] = df_transformed['StandardCost'] * 1.2

In [25]:
df_transformed.head()

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,ListPrice,Size,SizeRange,Weight,DaysToManufacture,ProductLine,DealerPrice,Class,Style,ModelName,LargePhoto,EnglishDescription,FrenchDescription,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status,Price
5,6,CA-5965,NaN,None,None,LL Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,L,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current,NaN
6,7,CA-6738,NaN,None,None,ML Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,M,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current,NaN
7,8,CA-7457,NaN,None,None,HL Crankarm,,,NaN,False,Black,500,375,NaN,None,NA,NaN,0,None,NaN,None,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current,NaN
10,11,CR-7833,NaN,None,None,Chainring,,,NaN,False,Black,1000,750,NaN,None,NA,NaN,0,None,NaN,None,None,None,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,None,None,None,None,None,None,None,None,None,2003-07-01,NaT,Current,NaN
209,210,FR-R92B-58,14.0,LB,CM,"HL Road Frame - Black, 58",,,NaN,True,Black,500,375,NaN,58,54-58 CM,2.24,1,R,NaN,H,U,HL Road Frame,b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...,Our lightest and best quality aluminum frame m...,Notre cadre en aluminium plus léger et de qual...,重量最轻、质量最好的铝制车架采用最新的合金材质；经过焊接和热处理，坚固牢靠。我们创新的设计确...,لقد تم صناعة هيكل دراجتنا الألومنيوم الأخف وزن...,מסגרת האלומיניום הקלה והאיכותית ביותר שלנו עשו...,เฟรมอลูมิเนียมคุณภาพสูงสุดและน้ำหนักเบาที่สุด ...,Unser leichtester und hochwertigster Aluminium...,最新の合金で作られた最軽量/最高品質のアルミニウム フレームで、強度を得るために溶接および熱...,"""En yeni alaşımdan imal edilme, en hafif ve en...",2003-07-01,NaT,Current,NaN

## Step 5: Load Data

#### Load Back to SQL Server

In [26]:

# Load the transformed data back to a new table in the database
df_transformed.to_sql('TransformedProducts', conn, if_exists='replace', index=False)

C:\Users\Admin\AppData\Local\Temp\ipykernel_28280\3355963909.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_transformed.to_sql('TransformedProducts', conn, if_exists='replace', index=False)

DatabaseError: Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'sqlite_master'. (208) (SQLExecDirectW); [42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)")

#### Export to CSV

In [ ]:
# Export the transformed data to a CSV file
df_transformed.to_csv('TransformedProducts.csv', index=False)

## Full ETL Example

In [ ]:
import pandas as pd
import pyodbc

# Step 1: Connect to SQL Server
conn_string = (
    "DRIVER={SQL Server};"
    "SERVER=your_server_name;"
    "DATABASE=AdventureWorksDW2022;"
    "UID=your_username;"
    "PWD=your_password;"
)
conn = pyodbc.connect(conn_string)

# Step 2: Extract
query = "SELECT * FROM DimProduct"
df_product = pd.read_sql(query, conn)

# Step 3: Transform
df_transformed = df_product[df_product['Color'] == 'Black']
df_transformed['Price'] = df_transformed['StandardCost'] * 1.2

# Step 4: Load
# Load to SQL Server
df_transformed.to_sql('TransformedProducts', conn, if_exists='replace', index=False)

# Optionally, export to CSV
df_transformed.to_csv('TransformedProducts.csv', index=False)

# Close the connection
conn.close()

## Summary

#### Extract: Use pandas and pyodbc to read data from SQL Server.
#### Transform: Clean and manipulate the data using pandas.
#### Load: Save the transformed data back to SQL Server or export it to a CSV file.